steps:
  - label: ':ruby: Tests'
    command:
    - auto/test
    agents:
      queue: devlob:staging

  - block: 'Release Gem'

  - label: ':rubygems: Push gem '
    branches: 'master'
    agents:
      queue: devlob:staging
    command:
    - auto/release
