steps:
  - label: ':ruby: Tests'
    concurrency_group: eks-in-a-box-tests
    concurrency: 1
    command:
    - auto/test
    agents:
      queue: devlob:staging

  - block: 'Release Gem'

  - label: ':rubygems: Push gem '
    branches: 'master'
    concurrency_group: eks-in-a-box-release
    concurrency: 1
    agents:
      queue: devlob:staging
    command:
    - auto/release
    artifact_paths:
    - 'pkg/*.gem'
